import JSZip from 'jszip';

export interface ShowPackage {
  fseq: Uint8Array;
  audio: Uint8Array;
  audioExt: 'wav' | 'mp3';
  /** Base file name without extension (both files must share it). */
  baseName: string;
  songTitle: string;
  bpm: number;
  durationS: number;
}

/** Known audio file extensions to strip; a bare "." (as in a song title like "Mr. Brightside") is left alone. */
const AUDIO_EXT_RE = /\.(mp3|wav|m4a|aac|flac|ogg|opus|webm|wma|aiff?)$/i;

export function sanitizeBaseName(name: string): string {
  const base = name
    .replace(AUDIO_EXT_RE, '')
    .replace(/[^A-Za-z0-9 _-]+/g, '')
    .trim()
    .replace(/\s+/g, '_')
    .slice(0, 40);
  return base || 'lightshow';
}

export function readmeText(p: ShowPackage): string {
  const mins = Math.floor(p.durationS / 60);
  const secs = Math.round(p.durationS % 60)
    .toString()
    .padStart(2, '0');
  return [
    `Tesla Light Show: ${p.songTitle}`,
    `Duration ${mins}:${secs}, ${p.bpm.toFixed(1)} BPM, generated by Tesla Dance Revolution.`,
    '',
    'HOW TO PLAY IT ON YOUR CAR',
    '1. Format a USB stick as exFAT or FAT32 (not NTFS).',
    '2. Copy the whole "LightShow" folder from this zip to the root of the stick.',
    `   It must contain ${p.baseName}.fseq and ${p.baseName}.${p.audioExt} with matching names.`,
    '3. Make sure the stick has no TeslaCam folder and no firmware/map update files.',
    '4. Plug it into a front USB / USB-C or glovebox port and wait a few seconds.',
    '5. In the car: Toybox > Light Show > Schedule Show and pick the custom show.',
    '',
    'Supported: Model S (2021+), Model 3, Model X (2021+), Model Y, Cybertruck',
    'on software 2021.44.25 or newer. Multiple shows on one stick need 2023.44.25+.',
    '',
    'Safety: park with room around the car. If you enabled closures (windows,',
    'liftgate, mirrors, door handles) they will move during the show.',
    '',
    'Format reference: https://github.com/teslamotors/light-show',
  ].join('\n');
}

export async function buildShowZip(p: ShowPackage): Promise<Blob> {
  const zip = new JSZip();
  const folder = zip.folder('LightShow')!;
  folder.file(`${p.baseName}.fseq`, p.fseq);
  folder.file(`${p.baseName}.${p.audioExt}`, p.audio);
  zip.file('README.txt', readmeText(p));
  return zip.generateAsync({ type: 'blob', compression: 'STORE' });
}

export function downloadBlob(blob: Blob, filename: string): void {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  setTimeout(() => URL.revokeObjectURL(url), 10_000);
}
